# Generated by Django 5.2.10 on 2026-01-27 16:05

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ['-is_boosted', '-last_bumped', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='campus',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='campus',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='campus',
            name='radius_miles',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='utilities_included',
        ),
        migrations.AddField(
            model_name='listing',
            name='air_conditioning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='balcony',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='bike_storage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='cable_included',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='dishwasher',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='doorman',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='duration_type',
            field=models.CharField(choices=[('fall', 'Fall Semester'), ('spring', 'Spring Semester'), ('summer', 'Summer'), ('winter_break', 'Winter Break'), ('spring_break', 'Spring Break'), ('thanksgiving', 'Thanksgiving Break'), ('full_year', 'Full Academic Year'), ('custom', 'Custom Dates')], default='custom', max_length=20),
        ),
        migrations.AddField(
            model_name='listing',
            name='electricity_included',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='elevator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='gas_included',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='gym',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='has_roommates',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='heating',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='internet_included',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='laundry_in_building',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='listing_type',
            field=models.CharField(choices=[('full', 'Full Apartment/House'), ('room', 'Single Room')], default='full', max_length=10),
        ),
        migrations.AddField(
            model_name='listing',
            name='number_of_roommates',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='parking_spaces',
            field=models.IntegerField(blank=True, help_text='Number of parking spaces', null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='pool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='posting_type',
            field=models.CharField(choices=[('offering', 'I am offering a sublet'), ('seeking', 'I am seeking a sublet')], default='offering', max_length=20),
        ),
        migrations.AddField(
            model_name='listing',
            name='roommate_gender',
            field=models.CharField(blank=True, choices=[('any', 'Any'), ('male', 'Male'), ('female', 'Female'), ('non_binary', 'Non-Binary')], default='any', max_length=20),
        ),
        migrations.AddField(
            model_name='listing',
            name='washer_dryer_in_unit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='water_included',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listingimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 1, 27, 16, 5, 6, 142919, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campus',
            name='school_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='campus',
            name='state',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='listing',
            name='last_bumped',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('rented', 'Rented')], default='active', max_length=20),
        ),
    ]
